# Generated by Django 5.0.6 on 2024-10-12 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("country_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "country_name",
                    models.CharField(blank=True, max_length=45, null=True),
                ),
            ],
            options={
                "db_table": "countries",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("like_id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "likes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vacation",
            fields=[
                ("vacation_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "vacation_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "vacation_description",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "vacation_img",
                    models.ImageField(
                        blank=True, null=True, upload_to="vacation_images/"
                    ),
                ),
                ("likes", models.IntegerField(blank=True, null=True)),
                ("vacation_days", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "vacations",
                "managed": False,
            },
        ),
    ]
