# Generated by Django 5.0.6 on 2024-10-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("role_name", models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                "db_table": "roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(blank=True, max_length=45, null=True)),
                ("last_name", models.CharField(blank=True, max_length=45, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=45, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "users",
                "managed": False,
            },
        ),
    ]
