# Generated by Django 5.0.6 on 2024-10-08 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": True},
        ),
    ]
